=== Ferreyd/Master/XML/out/production/XML/tp1jeremy/forrest.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT a (object)>
<!ATTLIST a
href NMTOKEN #REQUIRED
xlink:href NMTOKEN #REQUIRED
xlink:role CDATA #REQUIRED
xmlns:xlink CDATA #FIXED "http://www.w3.org/1999/xlink"
>
<!ELEMENT auteur (nom,prénom)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT description (a|hr|p|script)*>
<!ATTLIST description
Style NMTOKEN #REQUIRED
style NMTOKEN #REQUIRED
xml:space NMTOKEN #REQUIRED
xmlns CDATA #FIXED "http://www.w3.org/1999/xhtml"
>
<!ELEMENT document (titre,auteur,description,xml_parse,remarques)>
<!ELEMENT hr EMPTY>
<!ATTLIST hr width NMTOKEN #REQUIRED>
<!ELEMENT i (#PCDATA|b)*>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT object EMPTY>
<!ATTLIST object xlink:href NMTOKEN #REQUIRED>
<!ELEMENT p (#PCDATA|i)*>
<!ATTLIST p
align NMTOKEN #IMPLIED
xml:space NMTOKEN #IMPLIED
>
<!ELEMENT prénom (#PCDATA)>
<!ELEMENT remarques (#PCDATA)>
<!ELEMENT script (#PCDATA)>
<!ATTLIST script language NMTOKEN #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ATTLIST titre
Style NMTOKEN #REQUIRED
style NMTOKEN #REQUIRED
>
<!ELEMENT xml_parse EMPTY>
<!ATTLIST xml_parse processor NMTOKEN #REQUIRED>

=== Ferreyd/Master/XML/out/artifacts/tp_rest_maven/tp1jeremy/forrest.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE document SYSTEM "/home3/r/rj002007/workspace/xml/Jeremy/tp1jeremy/forrest.dtd">
<!-- ERREUR 7, 8 CORRIGEE : standalone  , iso-->
<?xml-stylesheet type="text/xsl" href="fg.xsl"?>
<!-- à relire -->
<?robots index="yes" follow="no"?>
<document>
    <titre style="bold" Style="big">Mes mémoires</titre>
    <auteur>
        <nom>Gump</nom>
        <prénom>Forrest</prénom>
    </auteur><!-- ERREUR 1 CORRIGE -->
 <description xmlns="http://www.w3.org/1999/xhtml"
style="bold" Style="big" xml:space="preserve"> 
        <!-- à partir d'ici, on peut utiliser
        des éléments HTML  <!&#45;&#45; et d'autres aussi &#45;&#45;>
        c'est pratique pour du contenu
        documentaire --> <!-- ERREUR 2, 9 CORRIGE -->
        <p xml:space="default" align="center">Ma maman disait <!-- ERREUR 4 CORRIGE : "center-->
            toujours : &#xA; "<i>la vie c'est comme une
                boîte de <b>chocolat</b>, on ne sait jamais
            sur quoi on va tomber</i>".</p> <!-- ERREUR 3, 10 CORRIGE -->
    <hr width="100"/> <!-- ERREUR 6 CORRIGE : valeur  pour width -->
    <a  xlink:href="bubbagump.avi"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        href="bubbagump.avi"
        xlink:role="mon film">
        <object 
                xlink:href="bubbagump.avi"/> <!-- ERREUR 11 CORRIGEE -->
    </a>
    <script language="JavaScript">
        <![CDATA[
            function check() {
                for (int i=10; i>0; i--) {
                    if ( a[b[i]] > ]]>5 ) break;
        }
        }
       <!-- ERREUR 12 CORRIGEE -->
        <!-- vérifier si la boucle doit s'écrire
        avec i&#45;&#45; et pas i++ --> <!-- ERREUR 13 CORRIGEE -->
    </script>
    <p>La suite, je ne m'en souviens plus...</p> <!--  ERREUR 5 CORRIGE : fin du </p> -->
    </description>
    <xml_parse processor="JAXP"/>

<remarques>
Mon document ne parse pas
</remarques>
</document> <!-- ERREUR 14 CORRIGEE -->
        <!-- il y a quelques erreurs ERREUR 15 CORRIGEE-->
