=== Ferreyd/Master/XML/out/artifacts/tp_rest_maven/tp4nicolas/zoo.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!ENTITY nourrir.gif SYSTEM "nourrir.gif" NDATA gif>

        <!ENTITY % block "p | info | danger | attention">
        <!ENTITY % inline "b | i | em | strong | stabilo | img">
        <!ENTITY % attractions "aquarium | vivarium | enclos | voliére">
        <!ENTITY % animal "nom, sexe, taille, poids, commentaire">
        <!ENTITY % animal-attr "
id ID #REQUIRED
espèce CDATA #IMPLIED
nom-savant CDATA #IMPLIED
photo ENTITY #IMPLIED
date-naissance CDATA #REQUIRED
">
        <!ENTITY % u-attr "
unité CDATA #REQUIRED
status CDATA #IMPLIED
">

        <!ELEMENT p (#PCDATA | %inline;)*>
        <!ELEMENT info (#PCDATA | %inline;)*>
        <!ELEMENT danger (#PCDATA | %inline;)*>
        <!ELEMENT attention (#PCDATA | %inline;)*>

        <!ELEMENT b (#PCDATA | %inline;)*>
        <!ELEMENT i (#PCDATA | %inline;)*>
        <!ELEMENT em (#PCDATA | %inline;)*>
        <!ELEMENT strong (#PCDATA | %inline;)*>
        <!ELEMENT stabilo (#PCDATA | %inline;)*>
        <!ELEMENT img EMPTY>
        <!ATTLIST img src ENTITY #REQUIRED>

        <!ELEMENT zoo ((%block;)*, (%attractions;))>

        <!ELEMENT aquarium (mammifères-marins, poissons?)>
        <!ELEMENT mammifères-marins (dauphins?, baleines?, orques?)>
        <!ELEMENT poissons (sélaciens)>

        <!ELEMENT vivarium (serpents?, arachnéens?)>
        <!ELEMENT serpents (boas?)>
        <!ELEMENT arachnéens (mygales?)>

        <!ELEMENT enclos (primates?, fauves?)>
        <!ELEMENT primates (gorilles?, orangs-outans?)>
        <!ELEMENT fauves (tigres?, lions?)>

        <!ELEMENT voliére (oiseaux-terrestres?, oiseaux-aquatiques?, rapaces?)>
        <!ELEMENT oiseaux-terrestres (autruches?)>
        <!ELEMENT pingouins EMPTY>
        <!ELEMENT oiseaux-aquatiques (pingouins?, manchots?)>
        <!ELEMENT rapaces (aigles?)*>

        <!ELEMENT dauphins (%block; | dauphin)+>
        <!ELEMENT dauphin (%animal;)>
        <!ATTLIST dauphin %animal-attr;>

        <!ELEMENT baleines (%block; | baleine)+>
        <!ELEMENT baleine (%animal;)>
        <!ATTLIST baleine %animal-attr;>

        <!ELEMENT orques (%block; | orque)+>
        <!ELEMENT orque (%animal;)>
        <!ATTLIST orque %animal-attr;>

        <!ELEMENT sélaciens (%block; | requin)+>
        <!ELEMENT requin (%animal;)>
        <!ATTLIST requin %animal-attr;>

        <!ELEMENT boas (%block; | boa)+>
        <!ELEMENT boa (%animal;)>
        <!ATTLIST boa %animal-attr;>

        <!ELEMENT mygales (%block; | mygale)+>
        <!ELEMENT mygale (%animal;)>
        <!ATTLIST mygale %animal-attr;>

        <!ELEMENT gorilles (%block; | gorille)+>
        <!ELEMENT gorille (%animal;)>
        <!ATTLIST gorille %animal-attr;>

        <!ELEMENT orangs-outans (%block; | orang-outan)+>
        <!ELEMENT orang-outan (%animal;)>
        <!ATTLIST orang-outan %animal-attr;>

        <!ELEMENT tigres (%block; | tigre)+>
        <!ELEMENT tigre (%animal;)>
        <!ATTLIST tigre %animal-attr;>

        <!ELEMENT lions (%block; | lion)+>
        <!ELEMENT lion (%animal;)>
        <!ATTLIST lion %animal-attr;>

        <!ELEMENT autruches (%block; | autruche)+>
        <!ELEMENT autruche (%animal;)>
        <!ATTLIST autruche %animal-attr;>

        <!ELEMENT pingoins (%block; | pingoin)+>
        <!ELEMENT pingoin (%animal;)>
        <!ATTLIST pingoin %animal-attr;>

        <!ELEMENT manchots (%block; | manchot)+>
        <!ELEMENT manchot (%animal;)>
        <!ATTLIST manchot %animal-attr;>

        <!ELEMENT aigles (%block; | aigle)+>
        <!ELEMENT aigle (%animal;)>
        <!ATTLIST aigle %animal-attr;>

        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT sexe (#PCDATA)>
        <!ELEMENT taille (#PCDATA)>
        <!ATTLIST taille %u-attr;>

        <!ELEMENT poids (#PCDATA)>
        <!ATTLIST poids %u-attr;>

        <!ELEMENT commentaire (#PCDATA | %block;)*>

=== Ferreyd/Master/XML/out/artifacts/tp_rest_maven/tp4xsltjeremy/zoo.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="zoo.xsl"?>
<!DOCTYPE zoo SYSTEM "zoo.dtd" [
<!ENTITY % notations SYSTEM "notations.ent">
%notations;
<!ENTITY flipper.jpg SYSTEM "flipper.jpg" NDATA jpg>
<!ENTITY oum.jpg SYSTEM "oum.jpg" NDATA jpg>
<!ENTITY ecco.jpg SYSTEM "ecco.jpg" NDATA jpg>
]>

<zoo>
	<info>Ouvert de 6h18 a 18h25</info>
	<info><img src="nourrir.gif" />Il est <b>interdit</b> de nourrir les animaux&#127;&#128;.</info>
	
	<aquarium>
		<mammifères-marins>
			<dauphins>
				<dauphin id="a424242" photo="flipper.jpg" date-naissance="2013-01-01">
					<nom> Flipper </nom>
					<sexe> M </sexe>
					<taille unité="cm"> 240 </taille>
					<poids unité="kg"> 120 </poids>
				</dauphin>
				
				<dauphin id="z696969" photo="ecco.jpg" date-naissance="2012-06-15">
					<nom> Ecco </nom>
					<sexe> F </sexe>
					<taille unité="cm"> 202 </taille>
					<poids unité="kg"> 101 </poids>
				</dauphin>
				
				<dauphin id="r000007" photo="oum.jpg" date-naissance="2011-07-07">
					<nom> Oum </nom>
					<sexe> F </sexe>
					<taille unité="cm"> 150 </taille>
					<poids	unité="kg" status="mesure approximative"> 60 </poids>			
				</dauphin>	
			</dauphins>
		</mammifères-marins>
		<poissons>
			<sélaciens>
				<danger>Il est interdit de <b>nager</b> avec les requins</danger>
				<requin id="t1092001" espèce="marteau" date-naissance="1991-12-12">
					<nom>Oussama</nom>
					<sexe>M</sexe>
					 <taille unité="cm">455</taille>
					 <poids unité="kg">540</poids>
					 <commentaire>A tendance a se jeter contre les murs
						<![CDATA[<<< marteau & cinglé !!! >>>]]>
							<!-- Il faudra bien le faire piquer un jour -->
					 </commentaire>
				</requin>
				
				<requin id="vgyuh43" espèce="requin bleu" nom-savant="carcharias glaucus" date-naissance="2004-01-13">
					<nom>Saddam</nom>
					<sexe>M</sexe>
					<taille unité="cm">355</taille>
					<poids unité="kg" status="">425</poids>
				</requin>
			</sélaciens>
		</poissons>	
	</aquarium>
</zoo>

=== Ferreyd/Master/XML/Nicolas/tp1nicolas/zoo.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE document SYSTEM "zoo.dtd">
<zoo>
    <info>Coucou</info>
    <cage>
        <primates>
                <gorilles id="go01" date="2007-05-10">
                    <nom>Machin</nom>
                    <sexe>M</sexe>
                    <taille unite="cm">115</taille>
                    <poids unite="kg">164</poids>
                </gorilles>
                <babouins id="ba01" date="2007-05-10">
                    <nom>Wakatepe</nom>
                    <sexe>M</sexe>
                    <taille unite="cm">84</taille>
                    <poids unite="kg">35</poids>
                </babouins>
        </primates>
    </cage>
    <aquarium>
        <mammifères-marins>
            <dauphins>
                <dauphin id="jhgtr13" photo="flipper.jpg" date-naissance="1997-4-1">
                    <nom>Flipper</nom>
                    <sexe>M</sexe>
                    <taille unité="cm">215</taille>
                    <poids unité="kg">105</poids>
                </dauphin>
                <dauphin id="lkjh45" photo="ecco.jpg" date-naissance="2003-10-23">
                    <nom>Ecco</nom>
                    <sexe>F</sexe>
                    <taille unité="cm">202</taille>
                    <poids unité="kg">98</poids>
                </dauphin>
                <dauphin id="kjlhy90" photo="oum.jpg" date-naissance="1996-12-25">
                    <nom>Oum</nom>
                    <sexe>F</sexe>
                    <!-- c'est mon préféré -->
                    <taille unité="cm">295</taille>
                    <poids unité="kg" status="mesure approximative">190<!-- il faut refaire la pesée --></poids>
                </dauphin>
            </dauphins>
        </mammifères-marins>
        <poissons>
            <sélaciens>
                <danger>Il est <b>interdit</b> de nager avec les requins.</danger>
                <requin id="plojk09" espèce="marteau" date-naissance="1998-6-5">
                    <nom>Oussama</nom>
                    <sexe>M</sexe>
                    <taille unité="cm">455</taille>
                    <poids unité="kg">540</poids>
                    <commentaire>A tendance a se jeter contre les murs
                        <![CDATA[<<< marteau & cinglé !!! >>>]]>
                        <!-- Il faudra bien le faire piquer un jour -->
                    </commentaire>
                </requin>
                <requin id="vgyuh43" espèce="requin bleu" nom-savant="carcharias glaucus" date-naissance="2004-1-13">
                    <nom>Saddam</nom>
                    <sexe>M</sexe>
                    <taille unité="cm">355</taille>
                    <poids unité="kg" status="">425</poids>
                </requin>
            </sélaciens>
        </poissons>
    </aquarium>
</zoo>
